apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "powerdns.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "powerdns.name" . }}
    helm.sh/chart: {{ include "powerdns.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  01-general-config.conf: |
    {{ range $key, $value := .Values.powerdns.config -}}
    {{ $key }}={{ $value }}
    {{ end }}